### ISSUE TITLE
Specify WAF web ACL by name

### ISSUE THREAD

**Issue by atheiman** [kubernetes-sigs/aws-load-balancer-controller#1018]
Currently `alb.ingress.kubernetes.io/waf-acl-id` only supports WAF web ACL IDs (uuids). Example:

```
alb.ingress.kubernetes.io/waf-acl-id: 499e8b99-6671-4614-a86d-adb1810b7fbe
```

I'd like this to support selecting a WAF web ACL to attach by name as well. Example:

```
alb.ingress.kubernetes.io/waf-acl-id: my-waf-acl
```

The use case for this is I'd like to declare one WAF web ACL in my nonprod and prod accounts named `AcmeCorpWafAcl` and attach it to many nonprod and prod ALBs. I dont want each consuming application team to have to know the WAF web ACL ID in my nonprod and prod account and also to have to make this ID a parameter to their kubernetes deployment via helm value or whatever. To make it easier on consumers of the WAF web ACL, I'd like them to be able to simply specify the WAF web ACL name which can be consistent in each account we run our EKS clusters in.

<hr/>

This is setup is already supported for security groups - `alb.ingress.kubernetes.io/security-groups` both name or ID of securityGroups are supported.

**Comment by M00nF1sh** [comment]
This is valid use case.
I think we need to add a new annotation for this like `alb.ingress.kubernetes.io/waf-acl-name`. Since you can have two different web acl one with ID `499e8b99-6671-4614-a86d-adb1810b7fbe` and another one with name `499e8b99-6671-4614-a86d-adb1810b7fbe` too. 
I can do a PR later this week

**Comment by rdubya16** [comment]
@M00nF1sh Any progress on this PR? This would be a very useful feature for us as well.

**Comment by mike-stewart** [comment]
@M00nF1sh Is this feature still planned? Would make deployment a lot easier for us as well.

**Comment by fforloff** [comment]
Any update on this?

**Comment by M00nF1sh** [comment]
Hi guys,
The waf v1 have been deprecated, and we have added wafv2 support in both v1.1.9 and latest v2.0.0.
however, due to wafv2's API behavior, see [comment-1](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1089#issuecomment-573961747) [comment-2](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1089#issuecomment-591708879), we have to use an ARN instead name.

closing this issue.
