### ISSUE TITLE
aws-alb-ingress-controller failed to reconcile rules due to ListenerNotFound

### ISSUE THREAD

**Issue by muralindia** [kubernetes-sigs/aws-load-balancer-controller#1187]
This error is not related to ssl. I am applying this ingress, it created the alb but the alb is not loading the 2048 game. 

kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.4/docs/examples/2048/2048-ingress.yaml 

E0312 18:39:34.820561       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile listeners due to failed to reconcile rules due to ListenerNotFound: One or more listeners not found\n\tstatus code: 400, request id: 3c7bd120-f4de-44c9-82fb-93113889ef34"  "controller"="alb-ingress-controller" "request"={"Namespace":"2048-game","Name":"2048-ingress"}
I0312 18:39:36.283854       1 rules.go:60] 2048-game/2048-ingress: creating rule 1 on arn:aws:elasticloadbalancing:us-east-1:<>:listener/app/ebf6c982-2048game-2048ingr-6fa0/d2b7f0ab6e9e48aa/fc7b3bc754e4b3c4

**Comment by marceiriarte** [comment]
same problem here.

**Comment by threesquared** [comment]
I had this same issue after I had made some changes to the IAM Role. Deleting the namespace and re-creating everything made it work in the end.

**Comment by ecerulm** [comment]
I had the same problem it seems that if it fails to create the ALB initially then any other attempt to reconfigure the ingress will end up failing because it seems that it remembers the ARN of the Listener that failed to create `arn:aws:elasticloadbalancing:eu-west-1:xxxxx:listener/app/yyy/xxx/zzz` and tries to reconfigure which obviously fails. 

I had to delete the ingress and create again 
   
    kubectl -n my-namespace delete -f specs/pro/085-ingress.yaml
    kubectl -n my-namespace apply -f specs/pro/085-ingress.yaml

It would be good if aws-alb-ingress-controller would recognize if the listener ARN is non-existing and tries to create a new instead.

**Comment by yulibaozi** [comment]
it's ok by recreate ingress

**Comment by kishorj** [comment]
This should be addressed in 2.0 release where we retry creating the listener rule in case of error. It is due to the eventual consistency of the listener rules on the AWS side.

**Comment by kishorj** [comment]
Closing the issue for now. If you still see errors, feel free to reopen it.
