### ISSUE TITLE
[Feature Request] host multiple version docs

### ISSUE THREAD

**Issue by tnimni** [kubernetes-sigs/aws-load-balancer-controller#1559]
Getting 404 on: https://kubernetes-sigs.github.io/aws-alb-ingress-controller/

Also can you please make sure v1 and v2 docs live side by side?

thanks

**Comment by M00nF1sh** [comment]
@tnimni Do you have use case that rely on the old github pages doc? the old doc's markdown is still in the master branch.
the github pages url cannot be perserved after we rename the repo.

**Comment by benjamin-tucker** [comment]
Awesomes they working now :-). Can't wait to test drive this - thanks to all contributors ❤️

**Comment by tnimni** [comment]
@M00nF1sh yes I have a use case the rely on the old docs

I already figured out they are in the code and got it resolved just opened the issue to let you guys know

**Comment by codeasashu** [comment]
@M00nF1sh Where are the installation instructions in the new docs?

**Comment by M00nF1sh** [comment]
@codeasashu 
Hi, the docs are available below :D 
[Installation](https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/controller/installation/)
[Migration from v1](https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/upgrade/migrate_v1_v2/)

**Comment by myersjustinc** [comment]
My use case for the old docs was that I haven't migrated yet to the new version. Even if the URLs break due to how GitHub Pages handles things (totally understandable), it'd be helpful to have the different versions' docs available side by side, much like how Kubernetes itself handles docs and like many languages do.

It's helpful that the old docs are available by viewing old commits (and thank you for that reminder!), but they aren't rendered as helpfully as they were online—I'm resorting instead to using the Wayback Machine ([example](https://web.archive.org/web/20200508053331/https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/)), which I'm certainly willing to do but seems a bit much for something that was current just last week.

**Comment by M00nF1sh** [comment]
@myersjustinc we are  experimenting to have a multi-version docs :D

**Comment by myersjustinc** [comment]
That's great to hear—thank you!

**Comment by M00nF1sh** [comment]
Hi guys,
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v1.1/ is alive now, and our page supports multiple version. 

closing this
