### ISSUE TITLE
nlb ip, what is the min requirement for eks/kubernetes?

### ISSUE THREAD

**Issue by jurgenweber** [kubernetes-sigs/aws-load-balancer-controller#1745]
[this](https://github.com/aws/containers-roadmap/issues/981#issuecomment-715571153) says eks 1.18

[this](https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/service/nlb_ip_mode/) says kubernetes 1.20...

specifically looking at service type loadbalancer. I have run it up on eks 1.18 and it looks to be working, more testing required.

**Comment by kishorj** [comment]
The AWS cloud-provider fix needed for NLB IP is included in Kubernetes 1.20 and later. We backported the changes to EKS 1.18 release. This is the updated documentatoin - https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/service/nlb_ip_mode/.

New platform releases of EKS 1.16 and 1.17 also support the NLB IP mode.

**Comment by jurgenweber** [comment]
nice, thank you!

**Comment by mantasmatelis** [comment]
@kishorj, what was the backported fix?

I'm able to use the aws-load-balancer-controller to create and manage an NLB backed by pod IPs using Kubernetes 1.15.10 (self-managed, not EKS) with:
```
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
```

Is there an issue I'll run into if I'm on 1.15.10 and not 1.20?

**Comment by kishorj** [comment]
We don't recommend configuring nlb-ip on 1.15 using k8s service of type LoadBalancer. If you do, you will end up with two NLBs - one created by the in-tree controller, and another by the AWS load balancer controller. You'd need the fix similar to the PR https://github.com/kubernetes/kubernetes/pull/92839 on your in-tree controller.

For 1.15, you can use service of type NodePort instead of LoadBalancer with the nlb-ip annotatoin.

**Comment by JustinTArthur** [comment]
@kishorj thanks. In the case of using a `NodePort` in older Kubernetes, I assume the exposed node port is not actually used by the created NLB and is just a side effect?
