### ISSUE TITLE
EKS - service lb adding additional sg entry to worker node groups

### ISSUE THREAD

**Issue by shivani-hotstar** [kubernetes-sigs/aws-load-balancer-controller#1767]
When i am creating a kubernetes load balancer type service . It adds the load balancer security group to worker node group security group as an inbound rule . Which i don’t want.

The service config i am using .

`kind: Service
apiVersion: v1
metadata:
  name: hello-world
  namespace: test
  annotations:
    service.beta.kubernetes.io/xyz-load-balancer-healthcheck-request: /
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 127.0.0.1/32
  selector:
    app: hello-world
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: web`

Aws load balancer version i am using .
`602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.0.1`

My worker sg is already opened for all-traffic from vpc-cidr range. so no need of these entries here.

**Reason** 
why i don’t want load balancer sg entries to worker node group sg . Because of sg rule limit .

Same config is working fine under kops (1.17) but not in eks(1.18)

**Comment by M00nF1sh** [comment]
@shivani-hotstar
this issue should be long to https://github.com/kubernetes/kubernetes repo. 

With the config you provided, it will provision an CLB(classic LoadBalancer), which is supported by the in-tree controllers built inside k8s. The default logic will create a SG for LB and grant ingress permission to allow traffic from SG-For-LB to each worker nodes.  we currently do not have annotations to override this behavior. I assume it worked on k8s because u disabled worker node securityGroup managed via control-plane flags(which is enabled and cannot be disabled in EKS environment).

**Comment by sppwf** [comment]
Hi,

@M00nF1sh you are right, with this config, Kubernetes will add CLB. 
However the idea with ALB controller is the same. ALB Controller will add for each ALB new entry in node Security Group. If it reaches the Limit (60 by default - You can have 60 inbound and 60 outbound rules per security group), ALB controller will fail to add finish the configuration (basicaly it will not add targets to Traffic Group). AWS Allows to increase the limit however there are some implications. 

Sollution can be:
1. allow specifying multiple NodeSG to update and go to next one if limit is reached 
2. allow to not to add Security Group Inbound entry assuming that Administrator had allready added one. 

Thanks
Sergiu Plotnicu
