### ISSUE TITLE
Migration from v1 to v2 results in downtime due to no registered targets

### ISSUE THREAD

**Issue by enummela** [kubernetes-sigs/aws-load-balancer-controller#1790]
Hello, I followed all of the steps in the [upgrade guide](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/upgrade/migrate_v1_v2/), going from ALB Ingress Controller 1.1.5 to AWS Load Balancer Controller 2.1.1. The upgrade caused all of the targets from our existing ALB target groups to be unregistered and I cannot figure out what went wrong. No matter what I try the targets never become registered again. There are no errors to report according to the ALB Load Balancer Controller logs - just messages stating `successfully deployed model`. I have attached a sample ingress object from our cluster below. Note that only annotations supported by v1 are included.

[ingress.yaml](https://github.com/kubernetes-sigs/aws-load-balancer-controller/files/5906936/code-stdin-qwl.txt)

**Comment by M00nF1sh** [comment]
@enummela 
Hi, migrating from v1 to v2 shouldn't have deregistered the targets. 
would you share the model definition json in the controller logs(before the `successfully deployed model` log message)?

Also, it would be better if you can share with us your cluster ARN.

**Comment by enummela** [comment]
Hi @M00nF1sh, our cluster's ARN is `arn:aws:eks:us-west-2:021659412776:cluster/toothless`. FYI I already downgraded back to ALB Ingress Controller to fix the downtime issue. Fortunately I still have access to the [logs](https://github.com/kubernetes-sigs/aws-load-balancer-controller/files/5921935/logs.zip) from when AWS Load Balancer Controller was running in our cluster.

**Comment by enummela** [comment]
Update: I tried again and still all the targets are deregistered.

Right after installing AWS Load Balancer Controller Helm chart:

![Screen Shot 2021-02-04 at 12 36 52 PM](https://user-images.githubusercontent.com/5798441/106953773-a106fb80-66e7-11eb-87e9-260458a6ed36.png)

A few seconds later:

![Screen Shot 2021-02-04 at 12 51 37 PM](https://user-images.githubusercontent.com/5798441/106953846-be3bca00-66e7-11eb-9075-4da3e19a7ef6.png)

I collected some more logs ([aws-load-balancer-controller-logs.txt](https://github.com/kubernetes-sigs/aws-load-balancer-controller/files/5928452/aws-load-balancer-controller-logs.txt)) and the target group bindings ([targetgroupbinding.txt](https://github.com/kubernetes-sigs/aws-load-balancer-controller/files/5928461/targetgroupbinding.txt)).

**Comment by M00nF1sh** [comment]
@enummela Found the problem now 😄 
it's due to your node have the label: `alpha.service-controller.kubernetes.io/exclude-balancer: `false``.

In ALBController v1.15, in addition to check whether label `alpha.service-controller.kubernetes.io/exclude-balancer` exists on node, it also checks the whether value is `true`.
In later versions, e.g. ALBController v1.18, we changed the logic to only check whether label `alpha.service-controller.kubernetes.io/exclude-balancer` exists to match the logic in upstream kubernetes. 

In ALBController v2.0+, we use the same logic as ALBController v1.18(same logic as upstream kubernetes as well). Since your node have such label, it will be considered not part of the LB backends(even it have value false). that's why the controller removes the node from targetGroups.

You need to remove the label  from all your nodes.

**Comment by enummela** [comment]
@M00nF1sh you're right, `alpha.service-controller.kubernetes.io/exclude-balancer=false` was the problem. Your help with this is really appreciated. Thanks!

**Comment by M00nF1sh** [comment]
@enummela Glad able to help 😄 
closing this. feel free to open a new issue if there are further issue/questions 😃
