### ISSUE TITLE
Mutating webhook availability concerns

### ISSUE THREAD

**Issue by dudicoco** [kubernetes-sigs/aws-load-balancer-controller#1807]
Hi,

With the addition of the mutating webhook in v2 the aws-load-balancer-controller has become a cluster critical component. If the controller pods are not available to serve the mutating webhook requests **pods cannot be created within the cluster**.

This important detail is not documented anywhere, I ran into it during my tests of the new controller version.

I recommend the following to be documented:
1. The controller should run with minimum of two replicas, with leader election enabled
2. The controller should have a PDB of `maxUnavailable: 1`
3. The controller should have a priority class of `system-cluster-critical`
4. The controller should have a hard pod anti affinity with `topologyKey: kubernetes.io/hostname`

In addition to the above, the mutating webhook configuration can be changed so that pods can still be created if the controller is unavailable by changing the value of `failurePolicy` to `Ignore` - https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#failure-policy.

**Comment by M00nF1sh** [comment]
/kind documentation
Thanks for the valuable suggestions. I think we should make these changes into our default provided yamls. 
* The controller should have a PDB of maxUnavailable: 1
* The controller should have a priority class of system-cluster-critical
* The controller should have a hard pod anti affinity with topologyKey: kubernetes.io/hostname
* mutating webhook configuration by changing the value of failurePolicy to Ignore (only do this to pod)
As for below changes, i think we can document it in configuration section:
* The controller should run with minimum of two replicas, with leader election enabled

**Comment by dudicoco** [comment]
@M00nF1sh note that PDB should not be used with 1 replica as it will prevent the pod from ever being evicted from the node.
Also  pod anti affinity of `topologyKey: kubernetes.io/hostname` is not useful without at least two pods.

**Comment by M00nF1sh** [comment]
@dudicoco 
It's seems to be the right time to change it to be more than 1 replica. we will have to offer multiple replica install manifests before EKS provide managed addons.

**Comment by kishorj** [comment]
Latest helm chart for v2.2.0 release addresses the concerns. Here is the summary
- The default number of replicas is 2 with leader election enabled
- controller pod priority class is system-cluster-critical by default
- soft pod anti affinity with topologyKey: kubernetes.io/hostname, note we opted for soft anti-affinity instead of hard 
- PDB is not enabled by default, but you can specify during helm chart installation. Note: PDB will not be enabled if replicas is < 2.

pod mutating webhook failurePolicy is still set to Fail. We will consider this in future releases.


Closing the issue for now.
