### ISSUE TITLE
[Question] Attached to an already built ALB

### ISSUE THREAD

**Issue by AhmadMS1988** [kubernetes-sigs/aws-load-balancer-controller#1810]
Hi;
Can I attach the ingress target groups to a manually built ALB if I added the following tags to it?

ingress.k8s.aws/resource: LoadBalancer 
ingress.k8s.aws/stack: my-awesome-group
elbv2.k8s.aws/cluster: dev-eks

and annotate my ingress with
alb.ingress.kubernetes.io/group.name: my-awesome-group

or there are configs that are stored in a configmap or in Etcd?
Thanks

**Comment by M00nF1sh** [comment]
@AhmadMS1988 the controller is stateless. so if you tag the resources correctly, it will be picked up by the controller.

Just one caveat, if you delete the Ingress, the controller will try to delete the loadBalancer(as it thinks it owns it), is it the expected behavior for your use case? 
we'll add new annotation to allow user use a external LB without deletion the LB on Ingress deletion in the future.

**Comment by AhmadMS1988** [comment]
Thank you for your response;
Let's suppose I have two ingresses on the same group, if one of them deleted, will the alb be deleted, or will just be deleted if no other ingresses are defined on the same group.

**Comment by M00nF1sh** [comment]
@AhmadMS1988 
it will be deleted when no other ingresses are defined on the same group. 
when you delete a single Ingress while there are other ingresses within group, it merely cleanup rules for the deleted ingress from the ALB

**Comment by seivan** [comment]
@M00nF1sh Sorry to hijack this thread, but can you actually create an ALB outside of K8, and attach it via annotations alone? 
Will it set up targetGroupBindings and everything else?

**Comment by devprojectsme** [comment]
Dear @M00nF1sh , could you please provide any info or an url for further details on the: "we'll add new annotation to allow user use a external LB without deletion the LB on Ingress deletion in the future."?

Thanks in advance!
