### ISSUE TITLE
Services used by the controller.

### ISSUE THREAD

**Issue by adamdonahue** [kubernetes-sigs/aws-load-balancer-controller#1855]
This is not so much an issue as a question - but it might be worth documenting.

We run our services in an airgapped environment, and require VPC endpoints for any AWS service our EKS nodes access.  The ingress controller is not functioning because it can't reach several services we haven't created endpoints for.  We've been going through the logs (with debugging) and VPC flow logs and have determined we needed to add elasticloadbalancing and sts as additional endpoints.  

Issue is: what is the full list of endpoints required?

Also, I'd suggest moving timeouts connecting to services from debug to warning/error level.

Thanks.

**Comment by M00nF1sh** [comment]
@adamdonahue 
You can get the list of services from our iam policy: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy.json
In addition
1. `waf-regional`, `wafv2`, `shield` API access can be disabled via [flags](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/configurations/): `enable-shield`, `enable-waf`, `enable-wafv2`.
2. `cognito-idp` is only needed if cognito is configured on auth.

**Comment by bodgit** [comment]
I've just found this issue because I found the controller was trying to reach the waf service endpoint in my internal-only cluster and I was curious if I could just disable it altogether.

I agree with @adamdonahue that bumping the timeout error logging level would be super useful as this controller tries to talk to a lot of services by default which tends not to work in internal/airgapped environments and the observed behaviour is the controller just seems sluggish/slow to respond to new Ingress resources when it's trying to reach services which deliberately aren't accessible.

I'm going to now disable shield & waf altogether with the flags and see if that makes the controller a bit more responsive.

**Comment by adamdonahue** [comment]
> @adamdonahue
> You can get the list of services from our iam policy: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy.json
> In addition
> 
> 1. `waf-regional`, `wafv2`, `shield` API access can be disabled via [flags](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/configurations/): `enable-shield`, `enable-waf`, `enable-wafv2`.
> 2. `cognito-idp` is only needed if cognito is configured on auth.
> 
> Yes, it's a good idea to document this.
> 
> /kind documentation

Indeed - we disabled wafv2 and wafv1, which resolved the issue.

**Comment by mirodrr2** [comment]
@jbg, did you ever get an answer to this? Having the same problem. No VPC endpoints for WAFv2 three years later...
