### ISSUE TITLE
Private cluster not able to communicate ACM for certificate 

### ISSUE THREAD

**Issue by mohanrao** [kubernetes-sigs/aws-load-balancer-controller#1890]
I have a private cluster (with subnets ) and the vpc has endpoint to com.amazonaws.us-west-1.acm-pca. 

I have ingress resource create for HTTPS. 

I am seeing there error still in the controller 

RequestError: send request failed\ncaused by: Post \"https://acm.us-west-1.amazonaws.com/\": dial tcp 176.32.118.71:443: i/o timeout"

**Comment by M00nF1sh** [comment]
@mohanrao 
Hi, `acm-pca` is another service than `acm`.  and `acm` is currently not available from privateLink.
You need to use [`alb.ingress.kubernetes.io/certificate-arn`](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/ingress/annotations/#certificate-arn) annotation to explicit set the SSL cert instead of rely on cert auto-discovery(which requires access to acm service)

**Comment by mohanrao** [comment]
thanks @M00nF1sh . I will try that

**Comment by mohanrao** [comment]
It worked @M00nF1sh .
