### ISSUE TITLE
Migration of existing ALB into ALB Ingress Controller

### ISSUE THREAD

**Issue by heungh** [kubernetes-sigs/aws-load-balancer-controller#1938]
Hi, IHAC who want to migrate their services into EKS.
They have a big trouble because of their alb, which has a lot of rules( over 100). 
So it's not easy to confirm their service working well, even if they apply all rules to new alb ingress controller.
They also consider two target group and convert traffic to new alb ingress controller.
But they use Codedeploy so it's not possible.
I found the issue about this : https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/228 
It's closed but I want to open the issue and some improvement  about inconvenient situations.
Thank you!

**Comment by M00nF1sh** [comment]
@heungh 
I opened the that issue. (it's auto-closed due to inactivity).
I'm little confused by our use case, why cannot they recreate a new ALB and  new rules via Ingress?

And what do you mean by "They also consider two target group and convert traffic to new alb ingress controller.", is it means use k8s(with aws-load-balancer-controller) to manage two targetGroups, while manage the other target groups in their own solution(some kind of graceful migration?)
If so, we already have a feature called [TargetGroupBinding](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/targetgroupbinding/targetgroupbinding/) for this exact use case.

**Comment by heungh** [comment]
> @heungh
> I opened the that issue. (it's auto-closed due to inactivity).
> I'm little confused by our use case, why cannot they recreate a new ALB and new rules via Ingress?
> 
> And what do you mean by "They also consider two target group and convert traffic to new alb ingress controller.", is it means use k8s(with aws-load-balancer-controller) to manage two targetGroups, while manage the other target groups in their own solution(some kind of graceful migration?)
> If so, we already have a feature called [TargetGroupBinding](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/targetgroupbinding/targetgroupbinding/) for this exact use case.

Thank you for your attention to this matter.
This customer has a concern to have some mistake when they migrate all rules to the ingress controller at once. 
Of course, they can examine each rule before the migration, but it's not easy to check mistakes because of a lot of rules. 
So they consider the two target groups and convert their services to a new group, but they use codedeploy for application distribution, which can't have two target group.

**Comment by M00nF1sh** [comment]
@heungh 
sorry but I'm still not clear which feature is exactly need here.
Is it like updating a single targets with targets from k8s and targets from external application(out side of k8s)?
