### ISSUE TITLE
Error: conflicting tag(s)

### ISSUE THREAD

**Issue by Sebor** [kubernetes-sigs/aws-load-balancer-controller#1940]
It would be great to have ability to set different tags for different resources.
For example:
- alb.ingress.kubernetes.io/alb.tags
- alb.ingress.kubernetes.io/target-group.tags
- alb.ingress.kubernetes.io/security-group.tags

Because now I get the following error:
`{"level":"error","ts":<>,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"infra","namespace":"","error":"conflicting tag app: app-brocker | grafana"}`

**Comment by M00nF1sh** [comment]
@Sebor 
BTW, why would you use a different tag value for same tag key.

Currently our mental model is like this:
The tags annotation on Ingress will be applied to all Ingress related resources, including ALB/SG/TG
The tags annotation on Service will only impact service related resources, including TG.

That's why we merge the tags on service with tags on Ingress for TargetGroup.

**Comment by Sebor** [comment]
@M00nF1sh, sorry for delayed answer.
I have monitoring metrics based by tags, that's why I'd like to assign different tags.
But I've seen your mention:
> The tags annotation on Service will only impact service related resources, including TG

and now I think it is all what I need)

**Comment by M00nF1sh** [comment]
@Sebor 
Cool then. i'll close this issue.
Feel free to create a new one if you have further questions.
