### ISSUE TITLE
controller is stuck if one ingress has empty request condition

### ISSUE THREAD

**Issue by aandrushchenko** [kubernetes-sigs/aws-load-balancer-controller#2042]
Version: 2.1.1

Observed:
one of the ingresses has annotation:
```
alb.ingress.kubernetes.io/conditions.account-service-lumen-100716933: |                                                                                                                                                
  [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "HEADER","values":[""]}}]
```
the other ingress is not getting reconciled with error:
```
Failed deploy model due to ValidationError: A condition value cannot be empty
```

Expected:
broken annotations on one of the ingresses should not prevent reconciliation of the others

**Comment by kishorj** [comment]
@aandrushchenko, did you group the ingresses together into a single ingress group? if so, the error would impact the entire ingress group until the issue is fixed. 

In recent v2.2.0 release, we have made improvements to tolerate missing services, but validation error is still there. 

If the ingresses are independent or belong to different groups, error on one ingress would not affect other ingresses.

**Comment by aandrushchenko** [comment]
@kishorj you are right about the group, i forgot to mention this. shall we keep this issue open or there's already a known issue reported and prioritised?

**Comment by M00nF1sh** [comment]
we welcome PRs from community given this is a good first issue. 
We'll also evaluate and prioritize this internally if not taken by community members.

**Comment by r-erema** [comment]
I would like to take it
/assign @r-erema

**Comment by r-erema** [comment]
@aandrushchenko 
> one of the ingresses has annotation...
> the other ingress is not getting reconciled...

Could you provide full manifests of both ingresses, please?
