### ISSUE TITLE
Feature Request: NLB deletion protection

### ISSUE THREAD

**Issue by ttony** [kubernetes-sigs/aws-load-balancer-controller#2051]
Hi,

i would like to ask if the feature can be implemented?

**Comment by kishorj** [comment]
@ttony, thanks for bringing it up. 

We could add an annotation to support this 
```
service.beta.kubernetes.io/aws-load-balancer-attributes: deletion_protection.enabled=true
```

/kind feature

**Comment by JacekDuszenko** [comment]
Hey, I'd like to take a stab at implementing this :) 
/assign @JacekDuszenko

**Comment by JacekDuszenko** [comment]
On the ALB attributes annotation parsing we use a generic approach of parsing the whole config map provided by the `alb.ingress.kubernetes.io/load-balancer-attributes` annotation (https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/ingress/model_build_load_balancer.go#L280) whereas on the NLB we are essentially hardcoding supported lb attributes (https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/service/model_build_load_balancer.go#L234). 

I don't think that going with `service.beta.kubernetes.io/aws-load-balancer-attributes: deletion_protection.enabled=true
` annotation is a good idea here because this PR would have to include parsing all of the attributes in the form of a config map as well. I think this is a bigger change and should be done in a separate PR. This change would also involve changing the code in ingress to allow for code reuse.

What I propose instead and will implement in my PR is to use a different annotation specific to  `deletion_protection.enabled=true` attribute and implement it on a similar basis as the rest in (https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/service/model_build_load_balancer.go#L234).

I suggest that we create a boolean annotation `service.beta.kubernetes.io/aws-load-balancer-deletion-protection-enabled`

What do you think about this?

**Comment by kishorj** [comment]
@JacekDuszenko, I'm inclined more towards specifying load balancer attributes annotation since it will be consistent with the ALB. Here is what I recommend - 
1) Parse `service.beta.kubernetes.io/aws-load-balancer-attributes` into a string map
2) If there are specific annotations defined for access logs, cross zone load balancing, override the configmap from step 1.
3) Do not use a default values like we do currently. If we do this, the controller will ignore the attributes not specified via an annotation. The new behavior will be consistent with ALB.

Also deprecate the existing annotations to configure individual lb attributes, and remove the support in future releases.

There is no need to modify ingress code.

**Comment by JacekDuszenko** [comment]
OK, understood. This will take some more time but I'll be able to do it and submit a PR amendment shortly

**Comment by JacekDuszenko** [comment]
We should also think about reusing code from ingress, because service will use essentially the same code for attributes config map parsing

**Comment by kishorj** [comment]
> We should also think about reusing code from ingress, because service will use essentially the same code for attributes config map parsing

Ingress has other features like ingress groups, and also the annotations have different prefixes and keys. Other than building the model, we do have common code for NLB/ALB 😄

**Comment by JacekDuszenko** [comment]
Hey @kishorj, I faced a small issue while working on the task and could use your help. While parsing the config map we have nondeterministic ordering of particular properties because of how `range` on maps work. Tests at `model_builder_test.go` , particularly this line:https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/service/model_builder_test.go#L2100 assert the order of parsed properties json list. The question is how do we go about making this tests pass without introducing unnecessary changes in the production code. I was thinking of sorting the final result list, but doing it just to make tests pass is an exaggeration.

**Comment by JacekDuszenko** [comment]
Actually, I've just pushed my changes and they are available for the review. I haven't found a quick-win solution for the above issue and just went with sorting the keys alphabetically at the end. Please look into #2057 in your free time. Thanks!

**Comment by kishorj** [comment]
@JacekDuszenko, for deterministic test results, you can always sort and compare in the unit tests.

**Comment by JacekDuszenko** [comment]
Thank you very much for the quick review Kishor! I'll work on your comments and submit a fixed version shortly

**Comment by JacekDuszenko** [comment]
Hey, code is ready for the next review!
