### ISSUE TITLE
Edit button on Docs goes to 404

### ISSUE THREAD

**Issue by Yasumoto** [kubernetes-sigs/aws-load-balancer-controller#2266]
**Describe the bug**

The documentation's hardcoded link to submit a fix is not setup correctly.

**Steps to reproduce**

1. Open up [a documentation page](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/installation/)
2. Click the [`Edit this page`](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/edit/master/docs/deploy/installation.md) button
3. Receive a `404` instead

**Expected outcome**

1. Link to [the new `aws-load-balancer-controller` repo](https://github.com/kubernetes-sigs/aws-load-balancer-controller/edit/main/docs/deploy/installation.md)

I'd be happy to send over the change, but I couldn't quite figure out where this was set!

**Comment by kishorj** [comment]
@Yasumoto, thanks for bringing it up. This issue exist since we switched active development to 'main' branch starting v2, however, the mkdocs would still use the 'master' branch by default. Here is the diff that would fix the problem - 
```
diff --git a/mkdocs.yml b/mkdocs.yml
index cfdf4196..1ab6fc9a 100644
--- a/mkdocs.yml
+++ b/mkdocs.yml
@@ -1,6 +1,7 @@
 site_name: AWS Load Balancer Controller
 repo_name: kubernetes-sigs/aws-load-balancer-controller
 repo_url: https://github.com/kubernetes-sigs/aws-load-balancer-controller
+edit_uri: edit/main/docs/
 strict: true
 
 nav:
```

Feel free to raise a PR. Note: you can run `make docs-preview` at the top level to generate the docs preview locally.

**Comment by Yasumoto** [comment]
Submitted at https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2267; thanks for teaching a new contributor how to fish @kishorj ! 🙇🏼
