### ISSUE TITLE
ALB Support for Service NodePorts

### ISSUE THREAD

**Issue by johnkeates** [kubernetes-sigs/aws-load-balancer-controller#2347]
**Is your feature request related to a problem?**
I can't use ServiceAnnotations to attach Service NodePorts to an ALB. I cannot use an NLB because I need to use Security Groups. The Service resource is created by Istio as it is an IngressGateway.

**Describe the solution you'd like**
Annotations that allow ALB targets that are Services with NodePorts.

**Describe alternatives you've considered**
Putting an ALB in front of the NLB, doubling the LB-cost and LB-traffic. Not really what we want.

**Comment by M00nF1sh** [comment]
@johnkeates 
Not sure whether i understand this properly. 
Could you create an Ingress for your case which will result in a ALB to forward traffic to your NodePort services.

**Comment by johnkeates** [comment]
@M00nF1sh Yes, that is possible, there are many constructions where we can add something in between, but we don't really want to add anything in between.

The NLB can be directly attached to an Istio IngressGateway, but an ALB cannot (at least not via annotations). I also can't really find the reasoning or information on the choices why NLB was made to attach to Services directly and the ALB for Ingresses. Both types of LB have different properties that might very well apply in both scenarios.

Say I want an Ingress that doesn't do HTTP, I'd want an NLB, not an ALB for example (the inverse of what I want to do, an ALB for a NodePort on a Service, the service being an IngressGateway).

Or in a more graphical form:

I can do this:
`
┌─────────┐     ┌────────────────────┐
│ NLB     ├─────► IngressGateway     │
└─────────┘     └────────────────────┘
`

But I want to do this:
`
`
┌─────────┐     ┌────────────────────┐
│ ALB     ├─────► IngressGateway     │
└─────────┘     └────────────────────┘
`

**Comment by M00nF1sh** [comment]
@johnkeates 
But if you create an Ingress Object for your service, It will be setup a ALB that forward traffic to IngressGateway right?
The Ingress merely describes how the ALB rules like, in your case it's forwarding all requests to ALB(you can specify such rule by make Ingress.Spec.defaultBackend to be your NodePort service).

The traffic went directly from ALB to IngressGateway, Ingress Object is just an abstraction and didn't take traffic.

**Comment by johnkeates** [comment]
@M00nF1sh yes, there are many ways to work around it, but I still don't see why the LB Controller is limited to only NLB-for-NodePort and doesn't allow ALB-for-NodePort. 

We are already working around it, but extra work just because of an arbitrary rule that doesn't have any explanation is a bit strange to me.

**Comment by iAnomaly** [comment]
I wanted to add some color here because we're encountering an issue that is directly related to the limits of this design decision as @johnkeates is suggesting.

We're evaluating Traefik as an Ingress Controller for our clusters. We're currently using the workaround you suggested above @M00nF1sh: we create an Ingress object and target Traefik's Service in order to provision an ALB (because we want some of features exclusive to ALB like WAF).

The Kubernetes Ingress concept allows Ingress Controllers to update an Ingress `status.loadBalancer.ingress` field with its gateway hostname/IP. The in-tree AWS load balancer controller for example sets the Classic ELB's DNS. aws-load-balancer-controller sets the ALB's DNS. This is all great and well.

The problem comes when using an Ingress Controller or Service Mesh which uses a proxy as the gateway because those controllers update the Ingress `status.loadBalancer.ingress` field from their Service's `status.loadBalancer`. Here is Traefik's Ingress Controller's specific implementation as an example: https://github.com/juliens/traefik/blob/master/pkg/provider/kubernetes/ingress/kubernetes.go#L342 ingress-nginx does this too.

This is just one specific example why only being able to satisfy Ingress with ALB and Service with NLB have some major restrictions as @johnkeates has pointed out more generally. How significant would the LOE be for adding support for ALB on a Service type at least? I'm sure there are use cases for NLB on an Ingress type too but we haven't encountered those specifically.

Appreciate all that you have done and continue to do on this project @M00nF1sh @kishorj !
