### ISSUE TITLE
 TLS1.0 - Disable (or make configurable) for the controller webhook

### ISSUE THREAD

**Issue by gmorse-gd** [kubernetes-sigs/aws-load-balancer-controller#2368]
**Is your feature request related to a problem?**
TLS1.0 is outdated and can be seen as a security issue.

**Describe the solution you'd like**
I'd like TLS1.0 to be disabled or optionally/additionally add that configuration to be adjusted in the running deployment.

**Comment by M00nF1sh** [comment]
/kind feature
@gmorse-gd yeah, it's possible to enforce maybe tls 1.2 by default(since tls 1.3 is supported by k8s 1.19+ only), but would like to understand the implications:

1. what's the security risk of such TLS min version?
   from what i understand, the negotiation will pick the highest supported TLS version among client/server, so i suppose TLS1.3 will be picked by default.  Is the risk some other component talks to our webhook with lower TLS version?
2. supported TLS version from APIServer

**Comment by gmorse-gd** [comment]
@M00nF1sh thanks for the response.

For question 1, the concerns around TLS 1.0 is the ability to decrypt the traffic (or other exploits) if one was able to cause the client/server to negotiate to use that protocol. The protocol should be disabled, but I can't speak to the implications of point 2.

**Comment by M00nF1sh** [comment]
@gmorse-gd 
Thanks, i believe all eks supported k8s versions supports TLS 1.2, i'll double check it and set TLS 1.2 as minimal.
