### ISSUE TITLE
Can I use the aws-alb that I used to move the EKS cluster?

### ISSUE THREAD

**Issue by suhyun-baek** [kubernetes-sigs/aws-load-balancer-controller#2395]
Can I use the aws-alb that I used to move the EKS cluster?

I want to use the aws-alb that I used When my application move to new eks cluster.
I know that aws-load-balancer-controller find aws alb through tag when we use alb ingress.

ingress.k8s.aws/stack
ingress.k8s.aws/resource
elbv2.k8s.aws/cluster

I tested. 
- Update elbv2.k8s.aws/cluster Tag to new cluster. 
- Deploy Ingress to new cluster

I checked no downtime.
I am going to ues this way when move production cluster to new cluster.  Is there a problem?
I think this will be done once every 6 months.

**Comment by kishorj** [comment]
You can migrate the ALB to a different cluster by modifying the tags. However, you need to scale the lb controller deployment down to 0 replicas in the original cluster to prevent the controller from inadvertently modifying your AWS ALB resource while you make the changes.

**Comment by suhyun-baek** [comment]
We are planning to develop an automation process to move clusters using Tag in the future. 
Is there a possibility that the alb control will be changed due to Tag?

**Comment by kishorj** [comment]
@suhyun-baek, could you clarify what you mean by "Is there a possibility that the alb control will be changed due to Tag?" Did you mean whether the controller behavior of identifying resources via tag will change? The current behavior of identifying lb resources by tag will not change abruptly - unless we have a migration plan in place, we don't have any plans at the moment.

**Comment by kishorj** [comment]
@suhyun-baek, I'm closing the issue for now. If you have further concerns feel free to reopen or create a new issue.
