### ISSUE TITLE
Inaccessible from the public network

### ISSUE THREAD

**Issue by zops** [kubernetes-sigs/aws-load-balancer-controller#2417]
**Describe the bug**
Hello, I used EKS to create [2048](https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.2.0/docs/examples/2048/2048_full.yaml). I can access it inside the cluster, but I cannot access it on the public network.
![image](https://user-images.githubusercontent.com/76082537/146348479-c2a7ae8a-6e24-4d54-b5d1-74ad40025cdc.png)

**Steps to reproduce**

**Expected outcome**
I want to use the DNS of alb to access this project（2048）

**Environment**

* AWS Load Balancer controller version
* Kubernetes version 1.20
* EKS eks.3

**Additional Context**:
I checked the health check of ALB and it is not a problem. I also checked the rules of the security group, and there is no problem.
If you can answer my doubts, I will be very grateful！

**Comment by kishorj** [comment]
@zops, since your cluster is in the China region, the inaccessibility could potentially be due to the ICP license, could you check whether the license is applied to your account?

You could confirm whether the restriction is due to licensing by configuring the ALB to listen on ports other than 80, 443, or 8080. For example, you could specify the following annotation on your ingress to configure a listener on port 81 - 
```
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 81}]'
```

**Comment by zops** [comment]
hi @kishorj 
Thank you very much for your reply, it made me realize that I may not be careful enough to check.

Later, I found through inspection that the subnet where the tagged alb is located is not public (it can only access the public network-only out and not in).

Please forgive my carelessness.
thanks again.
