### ISSUE TITLE
helm delete does not remove default token

### ISSUE THREAD

**Issue by matti** [kubernetes-sigs/aws-load-balancer-controller#2472]
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2071#issuecomment-867859035

**Comment by kishorj** [comment]
It appears you've setup IAM role for service accounts (IRSA). In this case, you create the serviceaccount via eksctl (or a similar process), and the serviceaccount refers to the secret aws-load-balancer-controller-token-xxxxx. Since the serviceaccount did not get created by helm, it will not be removed on helm chart delete - this is not a problem with the chart.

If you used eksctl, you can delete the serviceaccount and the corresponding token as follows:
```
eksctl delete iamserviceaccount --cluster <cluster-name> --namespace kube-system --name aws-load-balancer-controller
```

I will add it to the uninstall steps in the charts README
