### ISSUE TITLE
Deregister nodes that are tainted by aws-node-termination-handler

### ISSUE THREAD

**Issue by tjs-intel** [kubernetes-sigs/aws-load-balancer-controller#2498]
**Is your feature request related to a problem?**
Nodes aren't deregistered when tainted by https://github.com/aws/aws-node-termination-handler, which can result in request errors when instances are later terminated.

**Describe the solution you'd like**
Nodes should be deregistered from target groups when tainted by the aws-node-termination-handler to prevent errors caused by terminating instances attached to load balancers. This appears to already be handled for the cluster-autoscaler, and the relevant changes might be added [here](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/9b3880fffc2680460436ff4bd462640a7bdc03b1/pkg/k8s/node_utils.go#L24-L34). aws-node-termination-handler creates a [handful of taints](https://github.com/aws/aws-node-termination-handler/blob/7040c8e46e18a1409650c673f3bbc3cccdcaddbf/pkg/node/node.go#L49-L60) that have the prefix `aws-node-termination-handler/`.

**Describe alternatives you've considered**
The [lifecycle-manager](https://github.com/keikoproj/lifecycle-manager) is unmaintained and advertises deregistering nodes from load balancers as a feature.

There is an outstanding [issue](https://github.com/aws/aws-node-termination-handler/issues/316) in the aws-node-termination-handler project, but I think the resolution should happen in this project.

**Comment by M00nF1sh** [comment]
i think it's better to modify the aws-node-termination-handler to apply the `node.kubernetes.io/exclude-from-external-load-balancers=true` label to nodes.

Generally taint(make node unschedulable) and whether node should be excluded from LB pool are two orthogonal event.
So it should be the aws-node-termination-handler's job to decide whether a node should be removed from LB pool or not(and apply correct labels to node).

e.g. if all your nodes are spot and are going to be terminated soon, then it should be marked as unschedulable, but not exclude from LB(since it will make your LB available immediately)

Thus, i believe the aws-node-termination-handler should be the authority to make such decision(whether to exclude node from LB pool) instead of the controller.

**Comment by tjs-intel** [comment]
I did not know about the `node.kubernetes.io/exclude-from-external-load-balancers=true` label, and you do propose a reasonable alternative. I thought this feature should be handled similarly to how the cluster autoscaler node removal is handled, but maybe the cluster autoscaler should also have a special case for this scenario.

One consideration with your suggested approach is that an administrator or other automated system may choose to apply that label. The aws-node-termination-handler should not ever attempt to remove that label if it was already applied by another person/system (that would potentially expose a node to a load balancer unintentionally). I'm not sure of the aws-node-termination-handler is capable of cancelling a termination event, but that is a scenario where the removal of the label would normally be reasonable.

**Comment by tjs-intel** [comment]
A PR has been approved in the aws-load-balancer-controller to handle this scenario https://github.com/aws/aws-node-termination-handler/pull/582
