### ISSUE TITLE
Set Health check of the target group from health check signals of pods

### ISSUE THREAD

**Issue by mohsen0** [kubernetes-sigs/aws-load-balancer-controller#2514]
**Is your feature request related to a problem?**

I was surprised when I deployed the controller with readiness gate enabled[1] to see the health checks need to be set as annotations[2] again since the readiness health checks are already on the pods[3].

[1] https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/pod_readiness_gate/

[2] https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#health-check

[3] https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

**Describe the solution you'd like**

If there is a path defined for pods health check readiness signal, that specification will be used for the health check of the target group, 

or if that does not exist, the liveness signal path can be used, 

and then if that does not exist or the checks are command-line scripts, a default setting can be used for the endpoint like (HTTP / 200 ).

**Describe alternatives you've considered**

Setting the health check annotations for ports, protocol, and paths, on the ingress object, but they already exist in pod's health check spec.

**Comment by kishorj** [comment]
It is difficult since health check config could use exec instead of TCP/HTTP. Also there could be different health check config for different pods, but AWS target group requires a single health check config for all the targets. The current default is to use the traffic-port for health check as well, you don't need to specify annotation to use the default.
