### ISSUE TITLE
Improves docs for Shared NLB for multiple deployments

### ISSUE THREAD

**Issue by mballoni** [kubernetes-sigs/aws-load-balancer-controller#2602]
I currently use the old fashioned ingress nginx-controller for an ELB.
We are planning on moving to a more modern (and future proof) NLB with a few extra configurations before (outside our EKS instance).

However we would like to keep a single NLB for all deployments/statefull sets/etc as we do with ingress nginx controller and it is not clear how we should do it with this project.

So my issue, at first, is how should we use this project to achieve this result? 
An ALB is not desired for us, specially one per Deployment due to costs management.

Any tips or docs would be highly appreciated, I googled a lot but it is not clear on how to do it or to understand if this is even possible.

Thank you

**Comment by kishorj** [comment]
You should be able to use NLB instead of classic LB for your nginx-controller setup with appropriate service annotations. 

If you don't want to forward traffic to nginx-ingress-controller, you could setup NLB target group to forward L4 traffic directly to your application. In case you want to share the same NLB across multiple deployments, you will have to create the NLB outside of the controller and use [TargetGroupBinding](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/targetgroupbinding/targetgroupbinding/) to associate each of the deployment with NLB target groups. If you follow this route, you won't be able to use the same listener port for multiple deployments.

You can share a single ALB with multiple deployments via the [ingress group](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#group.name) feature. You can create multiple deployment/ingresses and configure all of the ingresses to be part of the same group.

**Comment by mballoni** [comment]
Thank you, that's very helpful!

One main question that it's still not clear is whether or not the ingress nginx controller will stop supporting AWS load balancers (NLB) officially and if I should use this project to avoid further issues.

What would be your recommendation here? NLB is enough for my use case, we already have an external ALB and WAF setup that will route to either legacy or the new NLB that I've mentioned and deal with TLS termination.

Thank you!!

**Comment by kishorj** [comment]
@mballoni, 

It is up to the nginx project to recommend the appropriate type of load balancer to use. You could use both nginx and this controller simultaneously in your cluster since each of the controllers support different ingress classes.

NLB works at L4, so will be agnostic to the application protocol. ALB on the other hand works at L7 and is restricted to HTTP specific protocols only. It depends on your use case.

I'm closing the issue, if you have further concerns, feel free to reach out.
