### ISSUE TITLE
Stop overwriting helm chart version tags in-place

### ISSUE THREAD

**Issue by alfredkrohmer** [kubernetes-sigs/aws-load-balancer-controller#2605]
**Describe the bug**
Today it happened for the second time now that the Helm chart version 1.4.1 was overwritten, i.e. a new (changed) Helm chart tarball was uploaded for this version:
* SHA256 checksum of old version: `161024647775a591a1e445c70ca0ad5007f6df1ae1a3212f47c6b11e92e8c275`
* SHA256 checksum of new version: `27efedd381186f350ad10d56dd90c411e111485ccc055190b242977a3bd6f3f0`

We actually store and verify the checksum of the upstream Helm chart tarballs that we consume in our CI to prevent supply chain attacks and hence noticed this.

**Expected outcome**
When the Helm chart is updated, a new patch / minor / major version should be released instead of updating existing version tags.

**Comment by kishorj** [comment]
@alfredkrohmer, thank you for bringing it to our attention. The difference in checksum is due to the eks-charts release script where the existing tarball is replaced on each charts release - there are no changes to the chart otherwise.

Your concern is valid from the security standpoint, I will forward the issue to the eks-charts repository.

**Comment by kishorj** [comment]
@alfredkrohmer, I've fixed the chart release script to prevent overwriting existing packages. New eks-chart releases will not clobber existing packages. If you notice further issues, feel free to reach out to us.
