### ISSUE TITLE
Choose the ports to allow on nodegroup security group

### ISSUE THREAD

**Issue by NathanFRuiz** [kubernetes-sigs/aws-load-balancer-controller#2640]
**Is your feature request related to a problem?**
During PCI audition the port range used on the nodegroup security group was raised as a issue.

**Describe the solution you'd like**
A way to restrict the rule to specific ports or a way to disable the rule creation and let the admin create the rule by themself?

**Comment by kishorj** [comment]
@NathanFRuiz 
Since v2.3.0 release, controller adds port-range restricted security group rules to the nodegroup SGs. A user can choose to disable the security group rules management completely by creating a security group manually and specifying it via the `alb.ingress.kubernetes.io/security-groups` annotation on the ingress resource.

I'm closing the issue, let us know if you have further concerns.
