### ISSUE TITLE
ECDSA certificates are not found by auto-discovery

### ISSUE THREAD

**Issue by tavlima** [kubernetes-sigs/aws-load-balancer-controller#2671]
**Describe the bug**

ECDSA certificates are not found by auto-discovery

**Steps to reproduce**

1. import a ECDSA certificate into ACM, with a matching CN/SAN
2. create an ALB ingress object, with the same domain used by the certificate in (1). 
3. watch errors like "none cert found for: <domain>" in the AWS LBC pod logs

**Expected outcome**
The controller should be able to locate/discovery ECDSA certificates. Ideally, it should discovery any kind of certificate supported by ALBs.

**Environment**

* AWS LB controller v2.3.0
* Kubernetes v1.21
* EKS eks.6

**Additional Context**:

Just adding a RSA-2048 signed certificate to ACM, with the same domains, was enough to make the controller find the certificate.

**Comment by kishorj** [comment]
@tavlima, this is a known issue, the ACM ListCertificates API doesn't return ECDSA or RSA-4096 certificates unless explicitly specified. Issue #2719 provides more details. We will either make the key type configurable, or explicitly include the key types in the ACM queries.

Since we will use issue #2719 to track the effort, I will close this one as a duplicate.
