### ISSUE TITLE
Old LoadBalancer Doesn't Get Deleted After Reconciliation

### ISSUE THREAD

**Issue by akefirad** [kubernetes-sigs/aws-load-balancer-controller#2733]
**Describe the bug**
Old load balancer doesn't get deleted after reconciliation.

**Steps to reproduce**
(This is my case, not sure if there's other ways to reproduce the bug)
1. Deploy the AWS LB Controller with a wrong cluster name (interestingly despite what the docs says about the significance of correct value for `--cluster-name` the controller managed to deploy LB, maybe because my cluster is EKS?)
2. Create an ingress, watch the LB gets created with the wrong `elbv2.k8s.aws/cluster` tag.
3. Fix AWS LB Controller deployment with the correct cluster name and deploy it.
4. Watch the cluster, the controller tries to _reconcile_ the ingress and create a new LB.
5. Wait for "Successfully reconciled". You should see two LBs on AWS EC2 dashboard. 
6. If you remove the ingress, only the recent LB gets deleted.

**Expected outcome**
The old LB should be deleted after the new LB goes active.

**Environment**

* AWS Load Balancer controller version: Helm Chart 1.4.2
* Kubernetes version: v1.22
* Using EKS (yes/no), if so version? EKS 1.22 (eks.4)

**Additional Context**:
N/A

**Comment by kishorj** [comment]
@akefirad, the controller uses cluster-name to tag the AWS resources it manages. The subnet auto-discovery also utilizes cluster name based tags to filter subnets - since there are cluster management tools that tag the subnets with the cluster name. Since cluster name is specified via controller flags, it is not possible for an existing controller to keep track of the previous runs with a different flags. Besides, if the controller is to clean resources tagged for a different cluster, it becomes impossible to support multiple clusters in the same VPC.

**Comment by akefirad** [comment]
Thanks for the reply. Makes sense. Feel free to close the issue.
