### ISSUE TITLE
Target Group deregistering pods when reused for another set of pods with TargetGroupBinding

### ISSUE THREAD

**Issue by saha-rajdeep** [kubernetes-sigs/aws-load-balancer-controller#2757]
**Describe the bug**
We want to use the same targetgroup in an ALB/NLB to send traffic to two different clusters. This ALB/NLB is managed outside of the cluster. This is to enable fallback, as well as A/B testing. When we run TargetGroupBinding using targetGroupARN from one cluster (Using https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/targetgroupbinding/targetgroupbinding/), the target group registers the pods. But as soon as, we run TargetGroupBinding using the same targetGroupARN from another cluster, the new pods register, but pods from the first cluster deregisters.

**Steps to reproduce**
When we run TargetGroupBinding using targetGroupARN from one cluster, the target group registers the pods. But as soon as, we run TargetGroupBinding using the same targetGroupARN from another cluster, the new pods register but pods from the first cluster deregisters.

**Expected outcome**
Since we are using the same target group ARN, both set of pods should be registered in that target group, instead of de-registering the previous ones.

**Environment**

* AWS Load Balancer controller version: 2.4.2 
* Kubernetes version:1.22
* Using EKS (yes/no), if so version?yes, 1.22

**Additional Context**:

**Comment by kishorj** [comment]
The controller currently doesn't support sharing the same TargetGroupBinding across multiple clusters. This is expected behavior since controller assumes exclusive ownership over the target group binding. There is a feature request #2173 to support sharing tgb across multiple cluster/controllers. It is in our roadmap for the next minor release.

For ALB, you can use weighted target groups to split traffic between multiple clusters. Weighted target group feature is not available for NLB.

**Comment by saha-rajdeep** [comment]
Thanks Kishorj, that's what I suggested currently. However, customer is using NLB with NGINx ingress. Will keep an eye out for the next minor release.
