### ISSUE TITLE
Would removing first ingress object from the ingress group deleted ALB as well?

### ISSUE THREAD

**Issue by psyhomb** [kubernetes-sigs/aws-load-balancer-controller#2827]
**Describe the bug**
Hi, I have one question, let's say I have multiple grouped ingress objects and first one I've created was the one that triggered provisioning of the AWS ALB, what will happen if I try to delete that ingress object while other ingress objects that belong to the same group are still active and using ALB?

**Steps to reproduce**
I'm asking this question because I just tried to do that and I received a following error message in the log:

```plain
aws-load-balancer-controller-669bbc96c7-mqqrd {"level":"error","ts":1664999923.9415274,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"alb-1","namespace":"","error":"deletion_protection is enabled, cannot delete the ingress: my-first-service"}
```

It seems like AWS LBC just tried to delete ALB, luckily I have deletion protection enabled for this ALB, but my concern here and question is why AWS Load Balancer Controller would try to delete ALB when there is still ingresses objects (TG, rules...) that are using it?

**Expected outcome**
What I'd expect is that AWS LBC will trigger deletion of the ALB only if last ingress object belonging to the same ingress group is deleted.

**Environment**

* AWS Load Balancer controller version
v2.4.2

* Using EKS (yes/no), if so version?
v1.22

**Comment by psyhomb** [comment]
I just realized that `alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=true` annotation applies not only to ALB but also to individual ingress object, that's this operation is blocked and I'm seeing this error message.
It would be really helpful if this behavior could be explained in more details in the documentation, it is really confusing becasue I was 100% sure it only applies to ALB.

**Comment by M00nF1sh** [comment]
@psyhomb 
You are correct. We did an explicit check for `deletion_protection.enabled=true` when we handle Ingress deletions(not when handle ALB deletion). The original idea is explicitly alert users to confirm they want to delete the ALB/Ingress.

I agree there is some confusing here, as now this attribute applies to Ingress instead of the LoadBalancer. we'll need to revisit this to see what's the desired behavior.

The original change leading to our change is: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1900

**Comment by psyhomb** [comment]
@M00nF1sh 
Thank you for your reply. 👍🏼
