### ISSUE TITLE
Controller creates multiple target groups

### ISSUE THREAD

**Issue by jaksonwkr** [kubernetes-sigs/aws-load-balancer-controller#2843]
**Describe the bug**
I have the following scenario:
```
Ingress 1:
  target-type: ip
  healthcheck: /liveness
  host: auth.example.com
    path: /* -> service-auth

Ingress 2:
  target-type: ip
  healthcheck: /
  host: frontend.example.com
    path: /* -> service-frontend
    path: /auth -> service-auth
```
Both ingresses are on the same group and the controller is creating different target group for service-auth for each ingress and the problem is that the service-auth has a custom health check path which is not replicated into Ingress 2.
If I enable readiness gate the pods from service-auth never get ready because the target group from Ingress 2 never gets healthy

**Expected outcome**
Controller should use the same target group already created by the first service

**Environment**

* AWS Load Balancer controller version: v2.4.4
* Kubernetes version: 1.23.10
* Using EKS (yes/no), if so version? yes, eks.2

**Comment by M00nF1sh** [comment]
@jaksonwkr 
We choose to use a dedicated TargetGroup because we support define TargetGroup attributes from Ingress's annotation as well. So in theory, you can define different healthy check from the two Ingresses for same service, and that's why we created unique target group for Ingress+Service combination.
