### ISSUE TITLE
Karpenter with TargetGroupBinding is not working

### ISSUE THREAD

**Issue by abhiptl** [kubernetes-sigs/aws-load-balancer-controller#2926]
I am using karpenter as cluster Autoscaler to scale cluster EC2 instances based on load. In my EKS cluster we have multiple services running spread across different EC2 nodes. I never know on which node service is running and karpenter is also doing consolidation on time to time basic.

Now, I am trying to integrate AWS ALB Controller and specifically using TargetGroupBindings as I want to separate ALB resources creation. TargetGroupBindings provides nodeSelector to select nodes where services is running. Since, we never know which nodes are running service, it won't be possible to use TargetGroupBindings  with karpenter.

**Comment by kishorj** [comment]
What happens when you don't specify the nodeSelector, do all of your worker nodes get registered? It is up to you to work out the appropriate labels for your target nodes. In case of NodePort services, a subset of nodes will be able to forward traffic to your application potentially through an extra network hop. You could also use IP targets where the LB will forward the thraffic directly to your nodes.

**Comment by abhiptl** [comment]
I think IP target would better choice here as my application workload would not be deployed on "karpenter" nodes so nodeSelector would not work here. Thank you. We are good to close this.
