### ISSUE TITLE
Efficient Log Monitoring through Stream Differentiation

### ISSUE THREAD

**Issue by prysmakou** [kubernetes-sigs/aws-load-balancer-controller#3009]
**Is your feature request related to a problem?**
At the moment, logs of all types are directed to the same standard error stream. This makes it hard to distinguish between normal information messages, warnings, and errors.

**Describe the solution you'd like**
I propose that the Zap logger be reconfigured to separate log messages based on their type. This would allow error and warning messages to be sent to the standard error stream, while all other messages (such as info and trace) would be sent to the standard output stream.

**Describe alternatives you've considered**
As an alternative, we could continue to mix all log messages in the same stream, but this would make it difficult to quickly identify messages that require attention.

**Comment by oliviassss** [comment]
Hi thanks for the suggestion. I think in order to log to different stream based on the log level we need to custom [zapcore.NewTee](https://pkg.go.dev/go.uber.org/zap/zapcore#NewTee) with two or multiple cores, somthing like:

- one that locks zapcore.InfoLevel to stdout
- one that locks zapcore.DebugLevel to stderr

We will discuss this internally for the feasibility and priority.
