### ISSUE TITLE
Target Group Attributes applied but not removed (ALB)

### ISSUE THREAD

**Issue by vincentheet** [kubernetes-sigs/aws-load-balancer-controller#3096]
**Describe the bug**
When adding the annotation `alb.ingress.kubernetes.io/target-group-attributes` the attributes (e.g. stickiness.enabled=true) are applied correctly. When removing the annotation the attributes are not removed from the ALB. The documentation states:

> alb.ingress.kubernetes.io/target-group-attributes specifies [Target Group Attributes](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html#target-group-attributes) which should be applied to Target Groups.

That is correct those attributes are applied, but not removed. I'm not sure if that works as intended. If so I would like to propose (PR) a documentation change to clarify things.

**Steps to reproduce**
1.  Add the annotation: `alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60`
2. Verify in the AWS Console that stickiness is enabled on the ALB
3. Remove the just added annotation
4. Verify in the AWS console that stickiness is still enabled and not removed

**Expected outcome**
After removing the annotation `alb.ingress.kubernetes.io/target-group-attributes` the stickiness configuration should be removed.

**Environment**

* AWS Load Balancer controller version v2.4.2
* Kubernetes version 1.22
* Using EKS version 1.22

**Additional Context**:
Was able to verify this behaviour on two different clusters running the same EKS and AWS Load Balancer controller versions. Explicitly modifying the annotation to `alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=false` disabled the stickiness correctly (as shown by the AWS console).

**Comment by oliviassss** [comment]
Currently, the controller builds the TG attributes by parsing the annotation: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/0ad294b07eed49116a7dd19ab096f16197c38763/pkg/ingress/model_build_target_group.go#L433
So if the `stickiness` is once enabled, and then the annotation gets removed, the controller does not disable it since the annotation is empty. 
Yes, the workaround should be explicitly modify the annotation to `alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=false` to disable it.
Looks like a bug to me, or at least we need to improve the documentations. Will discuss internally
