### ISSUE TITLE
Gateway API Support 

### ISSUE THREAD

**Issue by sabinayakc** [kubernetes-sigs/aws-load-balancer-controller#3141]
**Is your feature request related to a problem?**
With the release of VPC Lattice and other gateway controllers, is there a plan to integrate ALB with the Kubernetes Gateway API? Or we should migrate towards AWS Gateway Controller 

**Describe the solution you'd like**
Creating Gateway Resources would create the required ALB, listeners and target groups.  

**Describe alternatives you've considered**
Using other Gateway Controllers.

**Comment by kishorj** [comment]
Gateway API backed by VPC lattice is different from the ones backed by ALB/NLB. Currently our plan is to provide the ALB/NLB backed Gateway API as orthogonal to the VPC lattice. We have a feature request #1338 to provide Gateway API using ALB/NLB. However, we are currently not able to deliver it as part of v2.5.0 due to lack of resources. We welcome community contribution for this.

**Comment by kahirokunn** [comment]
I need this.

**Comment by kahirokunn** [comment]
keep

**Comment by johngmyers** [comment]
This is a duplicate of #1338 
/close
