### ISSUE TITLE
cache TargetGroup tags to reduce number of DescribeTags calls

### ISSUE THREAD

**Issue by kishorj** [kubernetes-sigs/aws-load-balancer-controller#3171]
**Is your feature request related to a problem?**
In case of the a lot of target groups, for example 5K,  on a single VPC, and the VPC is shared across multiple k8s clusters and each cluster runs the LBC, the ingress reconciler encounters `ThrottlingException` for the the ELBv2 `DescribeTags` calls.

**Describe the solution you'd like**
Controller cache the TargetGroup tag information to reduce the number of API calls

**Describe alternatives you've considered**
A lower client side throttle configuration is not desirable as it slows down the reconcile of the ingress/service resources. Splitting the clusters across multiple VPCs would also require changes to the routing configuration.

**Comment by arkadiyt** [comment]
We're also running into this issue. Here are the top api calls made by our load balancer controller over a period of 24 hours - it seems like DescribeTags is taking 10x the volume of any other call and I believe it's causing us to run into very long sync delays:

![Screenshot 2023-05-18 at 4 33 12 PM](https://github.com/kubernetes-sigs/aws-load-balancer-controller/assets/2279289/0541bb58-d31a-411f-8398-ed5b98c99e9a)

**Comment by oliviassss** [comment]
@arkadiyt, we are supporting AWS RGT API to solve this issue since v2.5.2. You can check our [release note](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.5.2) for more detailed info on how to enable the RGT feature. 
I'm closing this issue as for now. Please feel free to reach out if you have any questions. Thanks
