### ISSUE TITLE
pod IPs registered to target group before joining service endpoint

### ISSUE THREAD

**Issue by yongzhang** [kubernetes-sigs/aws-load-balancer-controller#3197]
Hi, team

As described [here](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/targetgroupbinding/targetgroupbinding/#sample-yaml), `TargetGroupBinding` will reference the service and port, I thought IPs registered into the target group only come from IPs listed in service endpoints (kubectl describe service), but I observed that when my new pods were created, the IPs were registered into target group immediately before passing readinessProbe, is this the expected behavior?

**Comment by M00nF1sh** [comment]
@yongzhang 
We only consider pods in the service endpoints, however, unready endpoints will also be registered as long as it's containerReady and has the readinessGate injected by the ELB. (otherwise these pods show up in ready endpoints as we only mark the readinessGate as ready once it's registered to ALB and became healthy)
