### ISSUE TITLE
Is IMDSv2 max hops required to be >=2 if IRSA is configured?

### ISSUE THREAD

**Issue by MikeJansenNextira** [kubernetes-sigs/aws-load-balancer-controller#3358]
The [deploy docs](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/deploy/installation/#using-the-amazon-ec2-instance-metadata-server-version-2-imdsv2) say max hops for IMDS must be >= 2.

But [best practices](https://aws.github.io/aws-eks-best-practices/security/docs/iam/#restrict-access-to-the-instance-profile-assigned-to-the-worker-node) say to use IRSA and set max hops to 1, which totally makes sense to prevent pods from having access to the Instance Role.

If [IRSA is configured for AWS Load Balancer Controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/deploy/installation/#configure-iam), does it still require hops >=2 for IMDS?  Does it have other requirements for metadata introspection besides the Instance Role?

**Comment by oliviassss** [comment]
@MikeJansenNextira, thanks for reaching out. Quote from [EC2 official doc](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html#imds-considerations):

"In a container environment, we recommend setting the hop limit to 2.

The AWS SDKs use IMDSv2 calls by default. If the IMDSv2 call receives no response, the SDK retries the call and, if still unsuccessful, uses IMDSv1. This can result in a delay, especially in a container environment. In a container environment, if the hop limit is 1, the IMDSv2 response does not return because going to the container is considered an additional network hop. To avoid the process of falling back to IMDSv1 and the resultant delay, in a container environment we recommend that you set the hop limit to 2. For more information, see [Configure the instance metadata options](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-options.html)."

If you want to have the default hop limit as 1, you can pass the contrller flag `--aws-region` and `--aws-vpc-id`. Hope this helps.

**Comment by MikeJansenNextira** [comment]
@oliviassss Ok thanks.

So to validate I understand:

Setting hop = 1 is so that containers can't get access to the Node instance role (described [here](https://aws.github.io/aws-eks-best-practices/security/docs/iam/#restrict-access-to-the-instance-profile-assigned-to-the-worker-node)).  If hops = 2 then all containers have access to the instance role and associated permissions.  From my understanding, the whole purpose of IRSA is so that containers have their own permissions and not inherit the Node's permissions.  And the only way to restrict a container from assuming the Node role is via IMDS hops = 1 (inhibiting the container from getting the role session info from IMDS).

What you are saying then is that the only dependency that the AWS Load Balancer Controller has on IMDS if it's getting permissions via IRSA is the AWS Region and VPC ID, and that if I set hops = 1, then I just need to have those values passed as `--aws-region` and `--aws-vpc-id` ?

Thanks!

**Comment by mikestef9** [comment]
@MikeJansenNextira Your understanding is correct
