### ISSUE TITLE
AWS ALB controller manger is trying to create new load balancer instead of updating existing 

### ISSUE THREAD

**Issue by HanumanthaRAON** [kubernetes-sigs/aws-load-balancer-controller#3396]
**Describe the bug**
we are trying to modifying already existing load balancer routes and AWS load balancer controller is trying to create new ALB instead of updating existing ALB 

**Steps to reproduce**
Create a ALB using aws load balancer controller and create ALB with path based routing. try to modigy existing route or add new route to ALB 

**Expected outcome**
A concise description of what you expected to happen.
It is update existing ALB instead of creating new ALB

**Environment**

* AWS Load Balancer controller version  -- 2.6.1
* Kubernetes version -- 1.2.4.0
* Using EKS (yes/no), if so version? Yes

**Additional Context**:

**Comment by dex4er** [comment]
@HanumanthaRAON Hi. I fought with the same problem and finally I've got a setup where ALB is created with Terraform and Listener Rules, Target Groups (with Binding) and Security Groups are managed by AWS LB Controller.

Check https://github.com/dex4er/terraform-eks-flux-demo/blob/alb/alb_ingress.tf for Terraform and https://github.com/dex4er/terraform-eks-flux-demo/blob/alb/flux/infrastructure/aws-load-balancer-controller/ingress.yaml for Kubernetes config.

Sort explanation: all annotations for Ingress and all settings in Terraform must match, especially:

* Scheme of the ALB (internal or internet-facing)
* IP address type (ipv4 or dual)
* tags: elbv2.k8s.aws/cluster, kubernetes.io/cluster/NAME must be created in Terraform too, others from Terraform in default_tags for aws-load-balancer-controller

It is better do pre-create LB Listener in Terraform too because then it might be created Target Group that registers this ALB: it it will make the ALB *persistent*: AWS LB Controller won't delete it accidentally if some parameters mismatch.

**Comment by oliviassss** [comment]
Closing this issue as for now, please feel free to reach out if any concerns. Thanks

**Comment by FrederikNygaardSvendsen** [comment]
> @HanumanthaRAON Hi. I fought with the same problem and finally I've got a setup where ALB is created with Terraform and Listener Rules, Target Groups (with Binding) and Security Groups are managed by AWS LB Controller.
> 
> Check https://github.com/dex4er/terraform-eks-flux-demo/blob/alb/alb_ingress.tf for Terraform and https://github.com/dex4er/terraform-eks-flux-demo/blob/alb/flux/infrastructure/aws-load-balancer-controller/ingress.yaml for Kubernetes config.
> 
> Sort explanation: all annotations for Ingress and all settings in Terraform must match, especially:
> 
>     * Scheme of the ALB (internal or internet-facing)
> 
>     * IP address type (ipv4 or dual)
> 
>     * tags: elbv2.k8s.aws/cluster, kubernetes.io/cluster/NAME must be created in Terraform too, others from Terraform in default_tags for aws-load-balancer-controller
> 
> 
> It is better do pre-create LB Listener in Terraform too because then it might be created Target Group that registers this ALB: it it will make the ALB _persistent_: AWS LB Controller won't delete it accidentally if some parameters mismatch.

This is exactly what i was looking for - thanks for saving my day 🚀

**Comment by renatovieiradesouza** [comment]
@FrederikNygaardSvendsen work for me, tks. Can you help with example configuration to use same alb to differentes applications?
