### ISSUE TITLE
Versions in the helmchart not released correctly

### ISSUE THREAD

**Issue by Ilger** [kubernetes-sigs/aws-load-balancer-controller#3439]
**Describe the bug**
The versions of the helm chart of the last to releases are a version behind 

So the chart in the latest version are the ones of the previous

So tag v2.6.1 point to the chart with v2.6.0 same issue in the released assets.

The full.yaml is correct though

**Comment by oliviassss** [comment]
@Ilger, thanks, we'll investigate it. Meanwhile, can you refer to the `eks-chart` to install the controller via helm? The version should be aligned there.

**Comment by oliviassss** [comment]
The issue occurred in v2.6.1 and v2.6.0 code base, and it may be because of some flaw in the release activities, like we created the tag before bumping up the version, so the gh tag points to the wrong image tag in `helm/` manifest. But the tags are aligned in [eks-chart](https://github.com/aws/eks-charts), this issue only exists in our code base. We fixed it in recent v2.6.2 release.

Closing this issue as for now.
