### ISSUE TITLE
Targetgroupbinding doesn't register target pods in a peered VPC

### ISSUE THREAD

**Issue by easildur24** [kubernetes-sigs/aws-load-balancer-controller#3462]
Describe the bug
I created a target group in VPC 1 where my current load balancer is. My target pods are in a different VPC hosting the k8s cluster. When I created the targetgroupbinding, the pods are not registered. When I describe the targetgroupbinding, there's no event logged. Is this a missing feature in the CRD or did I do something wrong here?

I've tried this in the same VPC and it worked as intended.

Steps to reproduce
Create a target group in a VPC that's different from the k8s VPC.
Create the targetgroupbinding.

Expected outcome
The pods would be registered as targets under the target group.

**Comment by remi-hackle** [comment]
I am currently experiencing the same symptoms.
This is a setup that worked well before, but on newer EKS clusters, the 
service.beta.kubernetes.io/aws-load-balancer-nlb-target-type:"ip" is causing pods to not register in the target group.
We tracked down the symptom and found that the worker sg did not update the inbound rule for that sg or cird when in ip mode. 
However, when changing to service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance", the registration and inbound rule settings for the worker node sg worked fine.

I'd like to see a detailed guide to see if this is normal or if I need to do something different. 


test info
eks 1.27
aws-load-balancer-controller  v2.6.2

**Comment by easildur24** [comment]
I'm on EKS 1.25. Since this is a peered VPC(LB and target group in the same VPC, targets in another VPC), I cannot switch to instance mode, the target group has to be in ip mode. 

What did you mean by the work sg didn't update the inbound rule? I've added proper sgs and route tables and used VPC reachability analyzer to confirm that the pods are reachable from the LB ENI.

**Comment by marcosdiez** [comment]
I found the problem.

In order to add an IP to a target group in a different VPC, one must add the ` AvailabilityZone =all` to the `RegisterTargets` AWS API call. 

Source:

https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_TargetDescription.html

The ALB controller attempts to do that, by checking if the IP to be added is in the same network or not.
Unfortunately, though, if compares checks if the IP is in the belongs to the VPC of the *cluster* instead of the *ALB*.

Which means this comparison is always false.


I may write a proper fix, but for now I hard coded that:

https://github.com/marcosdiez/aws-alb-ingress-controller/commit/5d7edb415ad6a92c68ed4ad7db1c1f4f7cc98142

One can test it using the following container: marcosdiez/aws-load-balancer-controller:v2.7.0-m4

**Comment by marcosdiez** [comment]
@easildur24 @remi-hackle I believe I fixed the issue here #3570  . There is a docker container there with the fix. Also, please notice that one extra IAM permission is needed for the fix to work ( `elasticloadbalancing:DescribeLoadBalancers`, so `aws-load-balancer-controller` can get the subnets of the LB and check if `AvailabilityZone=all` needs to be added or not.

**Comment by ikosenn** [comment]
Different approach https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3479
