### ISSUE TITLE
Expose slow-start duration finished as (optional) readiness gate

### ISSUE THREAD

**Issue by hatmarch** [kubernetes-sigs/aws-load-balancer-controller#3506]
**Is your feature request related to a problem?**

This is a feature request concerning the ALB's s existing [slow start functionality](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html#slow-start-mode).  For pods (or "instances") assigned to target groups that have a slow start duration set, there is no authoritative way to know whether a given instance in that group has completed the slow start duration and is thus now eligible for its full share of traffic in the group.

This is important to our use case because we don't want to consider pods fully ready (in a k8s sense) until they have finished their slow start duration (and thus are "fully warmed") as our (Java) instances use that time to optimize their JVM and caches.

**Describe the solution you'd like**

Ideally we would like the load-balancer-controller (optionally) to inject a second readiness gate (similar to the [existing pod readiness gate](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/deploy/pod_readiness_gate/#:~:text=AWS%20Load%20Balancer%20controller%20supports,mutating%20webhook%20during%20pod%20creation.))  to pods that are assigned a target group with a slow start.  This new "slow-start readiness gate" should not be passed until the until slow start is finished for the instance in question.

This will likely require a new or updated API from the ALB itself (requiring tracking on a ticket like [this one](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1571))

**Describe alternatives you've considered**

We have written our own custom controller that polls the [describe-target-health](https://docs.aws.amazon.com/cli/latest/reference/elbv2/describe-target-health.html) API and starts a timer once a target becomes healthy. Once slow start duration has elapsed we clear the slow-start gate and allow the pod to become ready. If an instance becomes unhealthy in the target group, we stop the timer and unset the “warm” gate if it was previously set.

This approach is imperfect (and brittle) however since thee  is logic internal to the ALB  that is currently either opaque to us or hard to replicate accurately (such as when the slow-start timer for an instance is paused when the instance (temporarily) goes unhealthy (see also [here](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html)).

**Comment by M00nF1sh** [comment]
@hatmarch
thanks for the feature request. Below is my understanding per your description.

You are aiming to guarantee the JVM within new Pods undergoes full warm-up through incoming requests before proceeding deployment during a rolling upgrade. 
If so, i think this requested feature solves this problem in a indirect way, and replies on an assumption that “new pods starts to receive full traffic from ALB” means “new Pods’s JVM is fulling warmed up”. But this assumption is only true when there is high volume of traffic constantly.
I think an better and direct way to address this problem is to have an application specific readiness gate & corresponding controller, which probes certain endpoint on pod to check whether “JVM is fulling warmed up” before unblock a pod during deployment. However, this indeed requires you to write custom controllers per application(or a generic one if all your applications exposes similar JVM warmed up probe).

From my view point, relies on the assumption of `"new pods starts to receive full traffic from ALB" = "new Pod's JVM is fulling warmed up"` has no difference than the assumption of `"simply wait x duration after pods's registered to ALB" = "new Pod's JVM is fulling warmed up"`, which can be solved by either:
1. the solution you described, which polls [describe-target-health].
2. a generic controller, which injects a readiness gate and only marks it as ready when "all other readiness gate" became ready after X duration. (personally i think this one is better since it's generic and easy to implement, and don't increase AWS API usage)

**Comment by M00nF1sh** [comment]
@hatmarch 
I think it's a reasonable ask to expose such status from ALB API, we have forwarded the discussion to ELB team.

**Comment by oliviassss** [comment]
CC: @shraddhabang
