### ISSUE TITLE
Cert-manager dependency when no SSL connection is needed between the ALB and the pods.

### ISSUE THREAD

**Issue by Mohamed-Sharif** [kubernetes-sigs/aws-load-balancer-controller#3721]
**Is your feature request related to a problem?**
I am frustrated that cert-manager is needed when installing the load balancer controller even if it is not needed when there is no SSL connection between the ALB and the pods

**My Suggestion**
Either remove cert-manager from being a hard dependency when installing the AWS LBC or explain why it is needed in the first place if no encryption is required between the ALB and the pods.
Add a section in the documentation that explains Cert-manager use case within the LBC.

**Comment by oliviassss** [comment]
@Mohamed-Sharif if you're installing via helm chart, cert manager is not required. Iirc, the major reason we need to install cert manager when users are installing the controller via manifest is that, we need the cert manager to inject webhook cert in order to create the webhook successfully which is needed for the controller.
