### ISSUE TITLE
Ingress controller listen ports ValidationError

### ISSUE THREAD

**Issue by lemonshow** [kubernetes-sigs/aws-load-balancer-controller#525]
Still see listen port error with beta.5,
        image: quay.io/coreos/alb-ingress-controller:1.0-beta.5

error: error validating "abc-ingress.yaml": error validating data: ValidationError(Ingress.metadata.annotations.alb.ingress.kubernetes.io/listen-ports): invalid type for io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.annotations: got "array", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false

alb.ingress.kubernetes.io/listen-ports: [{"HTTP": 9001}]

**Comment by bigkraig** [comment]
The value of the annotation must be in quotes. Try putting it inside of ``'s

**Comment by etessari** [comment]
I'm currently using the image version v1.1.1, I'm deploying via helm chart and I'm always getting validation error for annotation parameter "**alb.ingress.kubernetes.io/listen-ports**":
`kubebuilder/controller "msg"="Reconciler error" "error"="listen-ports JSON structure was invalid: invalid character 'm' looking for beginning of value" "controller"="alb-ingress-controller"`

If I don't insert any value I have the above error, otherwise passing custom values I still have formatting issue, some examples:
`alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'`
`alb.ingress.kubernetes.io/listen-ports: '{0: {"HTTP": 80}}'`
I have already tried different formatting but can't figured out how to workaround the problem.

**Comment by M00nF1sh** [comment]
@etessari 
Hi, the `alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'` should worked out well. (I just tested it).

You can find examples on how to specify multiple ports: https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#listen-ports

**Comment by etessari** [comment]
Assigning service type "nodePort" seems to solve the issue, but with type "LoadBalancer" I still get the formatting issue.

**Comment by jrsalgado** [comment]
You can pass the array as text like this too
```yaml
annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/listen-ports: |
      [{"HTTP": 80}, {"HTTPS": 443}, {"HTTP": 8080}, {"HTTPS": 8443}]
```
